---
title: "Figure1"
output: html_document
date: "2024-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## codes for Figure 1

# loading libraries
```{r}
library(reshape2)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(gtable)
library(ggh4x)
library(broom)
library(vegan)
library(ggpubr)
library(stringr)
library(rstatix)
library(cowplot)
library(purrr)
library(SRS)
library(openxlsx)
library(ape)

```

# Figure 1d
```{r}
df1c <- read.delim("/Users/youche/Desktop/DOCK8_codes/Input_files/Fig1c_input.txt", header = TRUE, sep = "\t", colClasses = "numeric") 

p1c <- ggplot(df1c, aes(x=Samples)) +
  geom_smooth(aes(y=HPVs), method = "nls", formula=y~SSasymp(x, Asym, R0, lrc), se=F, linewidth=0.6, color="#2B7FB7") +
  geom_smooth(aes(y=Poly*15), method = "nls", formula=y~SSasymp(x, Asym, R0, lrc), se=F, linewidth=0.6, color="#D66027") +
  scale_y_continuous(
    name="Papillomaviruses",
    sec.axis = sec_axis(~./15, name="Polyomaviruses")
  ) +
  scale_x_continuous(
    breaks = c(1, 5, 10, 15, 20, 25)
  ) +
  theme_bw() +
  theme(
    axis.title.y = element_text(color="#2B7FB7"),
    axis.title.y.right = element_text(color = "#D66027"),
    axis.title.x = element_text(size = 10)
  ) +
  labs(x = "Number of samples") + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())

p1c
```

# Figure 1e
```{r}
df1d <- read.delim("/Users/youche/Desktop/DOCK8_codes/Input_files/Fig1d_input.txt", header = TRUE, sep = "\t", colClasses = c("factor", "factor", "factor", "numeric")) # input

df1d$subject_id <- factor(df1d$subject_id, levels = c("Pt01", "Pt02", "Pt03", "Pt04", "Pt05", "Pt06", "Pt07", "Pt08", "Pt09", "Pt10", "Pt11", "Pt12", "Pt13", "Pt14", "Pt15", "Pt16", "Pt17", "Pt18", "Pt19", "Pt20", "Pt21", "Pt22", "Pt23", "Pt24", "Hv01", "Hv02", "Hv03", "Hv04", "Hv05", "Hv06", "DPt07", "DPt08", "DPt09", "DPt10", "DPt14", "DPt15", "DPt18"))
df1d$kingdom <- factor(df1d$kingdom, levels = c("Bacteria", "Fungi", "Phage", "Eukaryotic virus"))
df1d$Group <- factor(df1d$Group, levels = c("Pre-Tx", "Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M","Post-Tx-onIS-6M","Post-Tx-onIS>12M","Post-Tx-offIS-12M","Post-Tx-offIS-24M","HVs", "Donor"))

p1d <- df1d %>% 
  filter(!Group=="Donor") %>% 
  ggplot(aes(x=subject_id, y = mean_abu, fill = kingdom)) +
  geom_bar(stat = "identity", position = "fill", width = 0.8) +
  scale_y_continuous(labels = function(x) x*100) +
  facet_grid(~Group, scales = "free_x", space = "free_x") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size=8, hjust=1, vjust=0.3), axis.title.x=element_blank(), axis.text.y=element_text(size=8), axis.title.y=element_text(size=10)) +
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank(), legend.title=element_text(size=10), legend.text=element_text(size=8)) + 
  ylab("Mean relative abundance (%)") +
  scale_fill_manual("Kingdom", values = c("#31a253", "#3073b9","#c793c2","#5d488b"))

p1d
```

# Figure 1f
```{r}
df1e <- read.delim("/Users/youche/Desktop/DOCK8_codes/Input_files/Fig1e_input.txt", header = TRUE, sep = "\t", colClasses = c("factor", "factor", "factor", "numeric")) # input

df1e$subject_id <- factor(df1e$subject_id, levels = c("Pt01", "Pt02", "Pt03", "Pt04", "Pt05", "Pt06", "Pt07", "Pt08", "Pt09", "Pt10", "Pt11", "Pt12", "Pt13", "Pt14", "Pt15", "Pt16", "Pt17", "Pt18", "Pt19", "Pt20", "Pt21", "Pt22", "Pt23", "Pt24", "Hv01", "Hv02", "Hv03", "Hv04", "Hv05", "Hv06", "DPt07", "DPt08", "DPt09", "DPt10", "DPt14", "DPt15", "DPt18"))
df1e$Group <- factor(df1e$Group, levels = c("Pre-Tx", "Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M","Post-Tx-onIS-6M","Post-Tx-onIS>12M","Post-Tx-offIS-12M","Post-Tx-offIS-24M","HVs", "Donor"))
df1e$Classification <- factor(df1e$Classification, levels = c("Others", "Anelloviridae","Herpesviridae", "Papillomaviridae","Betapapillomavirus", "Gammapapillomavirus", "Polyomaviridae", "Alphapolyomavirus", "Deltapolyomavirus", "Poxviridae", "Molluscipoxvirus"))

colors <- c("#F0F0F0", "#E0E4CC", "#a8e6ce", "#BDD7E7","#3182BD", "#08519C", "#FEE6CE", "#FDD0A2", "#F16913", "#faefbe", "#fccf09")

p1e <- df1e %>% 
  filter(!Group=="Donor") %>% 
  ggplot(aes(x = subject_id, y = mean_abu, fill = Classification)) +
  geom_bar(stat = "identity", position = "fill", width = 0.8) + 
  facet_grid(~Group, scales = "free_x", space = "free_x") +
  scale_y_continuous(labels = function(x) x*100) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size=8, hjust=1, vjust=0.3), axis.title.x=element_blank(), axis.text.y=element_text(size=8), axis.title.y=element_text(size=10)) +
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank(), legend.title=element_text(size=10), legend.text=element_text(size=8)) +
  ylab("Mean relative abundance (%)") + 
  scale_fill_manual("Viral classification", values = colors)

p1e
```

# Figure 1g
```{r}
df1f <- read.delim("/Users/youche/Desktop/DOCK8_codes/Input_files/Fig1f_input.txt", header = TRUE, sep = "\t", colClasses = c("character", "factor", "factor", "factor", "factor", "numeric", "numeric")) # input

df1f$site_specific <- factor(df1f$site_specific, levels = c("Ra", "Mb", "Vf", "Hp", "Ac", "Ic", "Pc", "Ph"))
df1f$subject_id <- factor(df1f$subject_id, levels = c("Pt01", "Pt02", "Pt03", "Pt04", "Pt05", "Pt06", "Pt07", "Pt08", "Pt09", "Pt10", "Pt11", "Pt12", "Pt13", "Pt14", "Pt15", "Pt16", "Pt17", "Pt18", "Pt19", "Pt20", "Pt21", "Pt22", "Pt23", "Pt24", "Hv01", "Hv02", "Hv03", "Hv04", "Hv05", "Hv06", "DPt07", "DPt08", "DPt09", "DPt10", "DPt14", "DPt15", "DPt18"))
df1f$Group <- factor(df1f$Group, levels = c("Pre-Tx", "Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M","Post-Tx-onIS-6M","Post-Tx-onIS>12M","Post-Tx-offIS-12M","Post-Tx-offIS-24M","HVs", "Donor"))

pre_postoff_12 <- c("Pt11", "Pt05", "Pt10", "Pt07", "Pt08", "Pt06", "Pt16", "Pt15", "Pt14", "Pt18", "Pt17", "Pt19", "Pt20")
pre_postoff_24 <-  c("Pt01", "Pt11", "Pt02", "Pt09", "Pt05", "Pt03", "Pt04", "Pt10", "Pt07", "Pt08", "Pt06", "Pt24")
pre_poston6 <-  c("Pt16", "Pt15", "Pt18", "Pt17", "Pt21", "Pt19", "Pt20")
pre_poston3 <-  c("Pt18", "Pt21", "Pt24", "Pt22", "Pt19", "Pt20", "Pt23")
pre_poston2 <- c("Pt22", "Pt20", "Pt23")
pre_poston1 <- c("Pt22", "Pt20", "Pt23")
pre_poston_12 <- c("Pt09", "Pt12", "Pt13")

# subset each group
df1f %>%
  filter(subject_id %in% pre_postoff_12) %>%
  filter(Group %in% c("Post-Tx-offIS-12M", "Pre-Tx")) -> df1h_pre_postoff12

df1f %>%
  filter(subject_id %in% pre_poston_12) %>%
  filter(Group %in% c("Post-Tx-onIS>12M", "Pre-Tx")) -> df1h_pre_poston12

df1f %>%
  filter(subject_id %in% pre_postoff_24) %>%
  filter(Group %in% c("Post-Tx-offIS-24M", "Pre-Tx")) -> df1h_pre_postoff24

df1f %>%
  filter(subject_id %in% pre_poston6) %>%
  filter(Group %in% c("Post-Tx-onIS-6M", "Pre-Tx")) -> df1h_pre_poston6

df1f %>%
  filter(subject_id %in% pre_poston3) %>%
  filter(Group %in% c("Post-Tx-onIS-3M", "Pre-Tx")) -> df1h_pre_poston3

df1f %>%
  filter(subject_id %in% pre_poston2) %>%
  filter(Group %in% c("Post-Tx-onIS-2M", "Pre-Tx")) -> df1h_pre_poston2

df1f %>%
  filter(subject_id %in% pre_poston1) %>%
  filter(Group %in% c("Post-Tx-onIS-1M", "Pre-Tx")) -> df1h_pre_poston1

# define function for paired comparisons
paired_comparison <- function(taxa, df, abu){
  df %>%
    group_by(variable, subject_id, site_specific, kingdom, Group) %>% 
    summarise(temp1 = sum({{abu}})) %>% 
    ungroup() %>% 
    group_by(subject_id, site_specific, kingdom, Group) %>% 
    summarise(mean_abu = mean(temp1)) %>% 
    ungroup() -> df_p
  
  df_p$mean_abu <- df_p$mean_abu*100
  df_p_temp <- df_p %>%
    filter(kingdom == {{taxa}}) %>%
    select(mean_abu, Group, site_specific, subject_id) %>%
    arrange(Group, subject_id) 
  
  col_viruses <- c("#5d488b", "#BCBDDC")
  col_bacteria <- c("#31a253","#A1D99B")
  col_fungi <- c("#3073b9","#9ECAE1")

  if (taxa == "Eukaryotic virus"){
    col = col_viruses
  }
  
  else if (taxa == "Bacteria"){
    col = col_bacteria
  }
  
  else if (taxa == "Fungi") {
    col = col_fungi
  }
  
  df_p_temp %>%
    group_by(subject_id, site_specific) %>% 
    summarise(num=n()) %>% 
    filter(num == 1) %>%
    unite("target", subject_id:site_specific) %>% 
    ungroup() %>% 
    .$target -> need_remove

  df_paired_wilcox <- df_p_temp %>%
    filter(!paste(subject_id, site_specific, sep = "_") %in% need_remove) %>%
    group_by(site_specific) %>%  
    wilcox_test(mean_abu~Group, data = ., paired = TRUE) %>% 
    ungroup() %>% 
    data.frame() %>% 
    mutate(p.adj=p.adjust(p, method = "BH")) %>% 
    mutate(taxa=taxa)
  
  p <- df_p_temp %>%
    filter(!paste(subject_id, site_specific, sep = "_") %in% need_remove) %>%
    ggpaired(x="Group", y="mean_abu", color = "Group", line.color = "gray", line.size = 0.1, point.size = 0.7, facet.by = "site_specific", short.panel.labs = FALSE, ncol =8, panel.labs = list(site_specific = c("Ra", "Mb", "Vf", "Hp", "Ac", "Ic", "Pc", "Ph"))) +
    scale_color_manual(values = col) + 
    theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank(), axis.title.y=element_text(size=10), axis.text.y=element_text(size=8)) +
    scale_y_continuous(limits = c(0,100)) +
    ylab("Mean relative abundance (%)") +
    stat_compare_means(paired = TRUE, size=3, aes(label = ..p.signif..)) +
    labs(color='Group') +
    theme(legend.title=element_text(size=10), legend.text=element_text(size=8), legend.key.size=unit(0.5, "cm")) +
    theme(legend.position = "none")
  return(list(p, df_paired_wilcox))
}

target_taxa <- c("Eukaryotic virus", "Bacteria", "Fungi")

df1h_pre_postoff12 %>% 
  filter(site_specific %in% c("Ra", "Vf", "Ac")) -> df1h_pre_postoff12_three_sites

# target three sites in main figure
p_pre_postoff12_highlight_3_sites <- map("Eukaryotic virus", paired_comparison, df1h_pre_postoff12_three_sites, relative_abu)
p1f <- cowplot::plot_grid(plotlist = lapply(p_pre_postoff12_highlight_3_sites, "[[", 1), ncol = 1)
p1f
```

# Figure 1h
```{r}
df1g <- read.delim("/Users/youche/Desktop/DOCK8_codes/Input_files/Fig1g_input.txt", header = TRUE, sep = "\t", colClasses = c("factor", "factor", "factor", "numeric", "numeric")) # input

df1g$group <- factor(df1g$group, levels = c("Pre-Tx", "Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M", "Post-Tx-onIS-6M", "Post-Tx-offIS-12M", "Post-Tx-offIS-24M"))
df1g$kingdom <- factor(df1g$kingdom, levels = c("Bacteria", "Fungi", "Eukaryotic virus"))
df1g$site_specific <- factor(df1g$site_specific, levels = c("Ra", "Mb", "Vf", "Hp", "Ac", "Ic", "Pc", "Ph"))
df1g$sd[is.na(df1g$sd)] = 0

p1g <- df1g %>% 
  filter(site_specific %in% c("Ra", "Vf", "Ac")) %>% 
  ggplot(aes(x=group, y=mean_fold, group=kingdom, color =kingdom)) +
  geom_point(size=0.7) +
  geom_line(size=0.5) +
  facet_grid(site_specific~.) +
  geom_errorbar(aes(ymin=mean_fold-sd, ymax=mean_fold+sd), width=.3, linewidth=.2) +
  scale_color_manual("Classification", values = c("#31a253", "#3073b9","#5d488b")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, size=8, hjust=1, vjust=0.3), axis.title.x=element_blank(), axis.text.y=element_text(size=8), axis.title.y=element_text(size=10)) +
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank(), legend.title=element_text(size=10), legend.text=element_text(size=8)) + 
  ylab("Genome equivalents log10 fold change")

p1g
```



