---
title: "Figure2"
output: html_document
date: "2024-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# loading libraries
```{r}
library(reshape2)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(gtable)
library(ggh4x)
library(broom)
library(vegan)
library(stringi)
library(gridExtra)
library(VennDiagram)
library(eulerr)
library(magrittr)
library(circlize)
library(ComplexHeatmap)
library(rsample)
library(randomForest)
library(ranger)
library(caret)
library(skimr)
library(RANN)
library(caretEnsemble)
library(combinat)
library(plotROC)
library(cowplot)
library(AmesHousing)
```


# Figure 2a
```{r}
df2a <- read.delim("/Users/chey2/Desktop/DOCK8_paper_codes/Input_files/Fig2a_input.txt", header = TRUE, sep = "\t", colClasses = c("factor", "factor", "factor", "factor", "factor", "numeric")) # input

df2a$grp <- factor(df2a$grp, levels = c("Pt01_Pre-Tx", "Pt02_Pre-Tx", "Pt03_Pre-Tx", "Pt04_Pre-Tx", "Pt05_Pre-Tx", "Pt06_Pre-Tx", "Pt07_Pre-Tx", "Pt08_Pre-Tx", "Pt09_Pre-Tx", "Pt10_Pre-Tx", "Pt11_Pre-Tx", "Pt12_Pre-Tx", "Pt13_Pre-Tx", "Pt14_Pre-Tx", "Pt15_Pre-Tx", "Pt16_Pre-Tx", "Pt17_Pre-Tx", "Pt18_Pre-Tx", "Pt19_Pre-Tx", "Pt20_Pre-Tx", "Pt21_Pre-Tx", "Pt22_Pre-Tx", "Pt23_Pre-Tx", "Pt24_Pre-Tx", "Pt20_Post-Tx-onIS-1M", "Pt22_Post-Tx-onIS-1M", "Pt23_Post-Tx-onIS-1M", "Pt20_Post-Tx-onIS-2M", "Pt22_Post-Tx-onIS-2M", "Pt23_Post-Tx-onIS-2M", "Pt18_Post-Tx-onIS-3M", "Pt19_Post-Tx-onIS-3M", "Pt20_Post-Tx-onIS-3M", "Pt21_Post-Tx-onIS-3M", "Pt22_Post-Tx-onIS-3M", "Pt23_Post-Tx-onIS-3M", "Pt24_Post-Tx-onIS-3M", "Pt15_Post-Tx-onIS-6M", "Pt16_Post-Tx-onIS-6M", "Pt17_Post-Tx-onIS-6M", "Pt18_Post-Tx-onIS-6M", "Pt19_Post-Tx-onIS-6M", "Pt20_Post-Tx-onIS-6M", "Pt21_Post-Tx-onIS-6M", "Pt09_Post-Tx-onIS>12M", "Pt12_Post-Tx-onIS>12M", "Pt13_Post-Tx-onIS>12M", "Pt05_Post-Tx-offIS-12M", "Pt06_Post-Tx-offIS-12M", "Pt07_Post-Tx-offIS-12M", "Pt08_Post-Tx-offIS-12M", "Pt10_Post-Tx-offIS-12M", "Pt11_Post-Tx-offIS-12M", "Pt14_Post-Tx-offIS-12M", "Pt15_Post-Tx-offIS-12M", "Pt16_Post-Tx-offIS-12M", "Pt17_Post-Tx-offIS-12M", "Pt18_Post-Tx-offIS-12M", "Pt19_Post-Tx-offIS-12M", "Pt20_Post-Tx-offIS-12M", "Pt01_Post-Tx-offIS-24M", "Pt02_Post-Tx-offIS-24M", "Pt03_Post-Tx-offIS-24M", "Pt04_Post-Tx-offIS-24M", "Pt05_Post-Tx-offIS-24M", "Pt06_Post-Tx-offIS-24M", "Pt07_Post-Tx-offIS-24M", "Pt08_Post-Tx-offIS-24M", "Pt09_Post-Tx-offIS-24M", "Pt10_Post-Tx-offIS-24M", "Pt11_Post-Tx-offIS-24M", "Pt24_Post-Tx-offIS-24M"))

df2a$Genus <-  factor(df2a$Genus, levels = c("Alphapapillomavirus", "Betapapillomavirus", "Gammapapillomavirus", "Deltapolyomavirus", "Molluscipoxvirus"))
df2a$Species <- factor(df2a$Species, levels = unique(df2a$Species[order(df2a$Genus)]))
df2a$Type <- factor(df2a$Type, levels = unique(df2a$Type[order(df2a$Genus)]))

df2a_mx <- df2a %>% 
  select(Type, grp, relative) %>% 
  spread(grp, relative) %>% 
  replace(is.na(.), 0) %>% 
  column_to_rownames(var = "Type")

sapply(strsplit(colnames(df2a_mx), "_"), "[[", 1) -> temp_name
colnames(df2a_mx) <- temp_name
row_order <- levels(df2a$Type)

column_split = c(rep("Pre-Tx", 24), rep("Post-Tx-onIS-1M", 3), rep("Post-Tx-onIS-2M", 3), rep("Post-Tx-onIS-3M", 7), rep("Post-Tx-onIS-6M", 7), rep("Post-Tx-onIS>12M", 3), rep("Post-Tx-offIS-12M", 13), rep("Post-Tx-offIS-24M", 12))

row_split = c(rep("Alphapapillomavirus", 1), rep("Betapapillomavirus", 27), rep("Gammapapillomavirus", 58), rep("Deltapolyomavirus", 3), rep("Molluscipoxvirus",1))
col <- colorRamp2(c(0, 0.05, 0.1, 0.5, 10, 50, 100), c("#F7F7F7",  "#9970AB", "#C2A5CF", "#E7D4E8", "#A6DBA0", "#5AAE61", "#1B7837"))
row_ha <- rowAnnotation(block = anno_block(gp = gpar(fill = c("#BDD7E7", "#3182BD", "#08519C", "#F16913", "#fccf09"))), width = unit(1, "mm"))

p2a <- Heatmap(as.matrix(df2a_mx),
                               row_order = row_order,
                               row_names_side = "left",
                               show_row_dend = F, 
                               show_column_dend = F,
                               col = col,
                               row_split = factor(row_split, levels = c("Alphapapillomavirus", "Betapapillomavirus", "Gammapapillomavirus", "Deltapolyomavirus", "Molluscipoxvirus")),
                               row_gap = unit(1, "mm"),
                               column_gap = unit(1.5, "mm"),
                               row_title = NULL,
                               column_split = factor(column_split, levels = c("Pre-Tx", "Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M", "Post-Tx-onIS-6M", "Post-Tx-onIS>12M",  "Post-Tx-offIS-12M", "Post-Tx-offIS-24M")),
                               cluster_row_slices = FALSE,
                               cluster_column_slices = FALSE, 
                               column_title = NULL, 
                               cluster_columns = FALSE, 
                               cluster_rows = FALSE,
                               left_annotation = row_ha,
                               #right_annotation = row_ha_ha_here,
                               row_names_gp = gpar(fontsize = 6),
                               column_names_gp = gpar(fontsize = 6)
                               ) 

p2a
```

# Figure 2b
```{r}
df2a %>% 
  group_by(grp) %>% 
  summarise(T_abu = sum(relative)) %>% 
  ungroup() %>% 
  data.frame() %>% 
  mutate(
    category = str_split(grp, "_") %>% sapply("[",2)) %>% 
  mutate(
    PID = str_split(grp, "_") %>% sapply("[",1)) -> df2a_bp

df2a_bp %>% 
  mutate(category_new = case_when(
  category %in% c("Post-Tx-onIS-1M", "Post-Tx-onIS-2M", "Post-Tx-onIS-3M", "Post-Tx-onIS-6M", "Post-Tx-onIS>12M") ~ "Post-Tx-onIS",
  category %in% c("Post-Tx-offIS-12M", "Post-Tx-offIS-24M") ~ "Post-Tx-offIS",
  TRUE ~ as.character(category)
)) -> df2a_bp_p

df2a_bp_p$category_new <- factor(df2a_bp_p$category_new , levels = c("Pre-Tx", "Post-Tx-onIS", "Post-Tx-offIS"))

p2b <- df2a_bp_p %>% 
  ggboxplot(x="category_new", y="T_abu", size = 0.1) +
  geom_jitter(aes(color=category_new), position = position_jitter(width = 0.15), size=0.8) +
  scale_color_manual(values =  c("#C7E9B4", "#7FCDBB", "#1D91C0")) + 
  geom_pwc(aes(group=category_new), method = "wilcox_test", label = "p.adj", p.adjust.method = "BH", size = 0.2, label.size = 2.5) +
  theme(axis.text.x=element_text(size = 8, angle = 45, hjust = 0.98, vjust = 0.98), axis.ticks.x=element_blank(), axis.title.x=element_blank(), axis.title.y=element_text(size=10), axis.text.y=element_text(size=8)) +
  ylab("Relative abundance of top 5 viruses (%)") +
  theme(legend.title=element_text(size=10), legend.text=element_text(size=8), legend.position = "right") +
  labs(color="Group")

p2b
```

# Figure 2c
```{r}
df2c <- read.delim("/Users/chey2/Desktop/DOCK8_paper_codes/Input_files/Fig2c_input.txt", header = TRUE, sep = "\t", colClasses = c("factor", "numeric", "numeric", "numeric", "numeric")) # input
df2c$Group <- factor(df2c$Group, levels = c("Pre-Tx", "Post-Tx-onIS", "Post-Tx-offIS", "HVs"))

p2c <- df2c %>%
  ggplot(aes(x = ratio, y = perc, fill=Group)) +
  geom_bar(stat = "identity", width=10) + 
  # scale_fill_manual(values = my_color_freq) + 
  scale_x_continuous(breaks = seq(from = 0, to = 100, by = 20)) +
  facet_grid(Group~.,space = "free_x") +
  theme_bw() + 
  scale_fill_manual("Group", values = c("#c7e9b4", "#7fcdbb", "#1d91c0", "#c51b8a")) + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
  ylab("Frequency of viruses (%)") + 
  theme(axis.text.x = element_text(size=8), axis.text.y = element_text(size=8), axis.title.x=element_blank(), axis.title.y=element_text(size=10))

p2c

```

# Figure 2d
```{r}
df2d <- read.delim("/Users/chey2/Desktop/DOCK8_paper_codes/Input_files/Fig2d_input.txt", header = TRUE, sep = "\t") # input

df2d %>% filter(new_grp == "Pre-Tx") %>% .$Type %>% unique() -> pre_uniq_types_f
df2d %>% filter(new_grp == "Post-Tx-onIS") %>% .$Type %>% unique() -> poston_uniq_types_f
df2d %>% filter(new_grp == "Post-Tx-offIS") %>% .$Type %>% unique() -> postoff_uniq_types_f
df2d %>% filter(new_grp == "HVs") %>% .$Type %>% unique() -> hv_uniq_types_f

pre_postoff_poston_hv = list()

pre_postoff_poston_hv[["Pre-Tx"]] = pre_uniq_types_f
pre_postoff_poston_hv[["Post-Tx-offIS-HVs"]] = c(postoff_uniq_types_f, hv_uniq_types_f) %>% unique()
pre_postoff_poston_hv[["Post-Tx-onIS"]] = poston_uniq_types_f

pre_postoff_poston_hv_euler <- euler(pre_postoff_poston_hv)
p2d <- plot(pre_postoff_poston_hv_euler, quantities = TRUE, fills = "transparent", lty=1:3, edges = c("#c7e9b4", "#7fcdbb", "#1d91c0"))
p2d
```

# Figure 2e and 2f
```{r}
df2e <- read.delim("/Users/chey2/Desktop/DOCK8_paper_codes/Input_files/Fig2e_input.txt", header = TRUE, sep = "\t", check.names = FALSE) # input

RF_test <- function(DF, pimp_feature="no"){
  set.seed(7)
  test_df <- {{DF}} %>% mutate(class = ifelse(cls == 1, "Y", "N")) %>% select(-c(cls))
  df_new <- test_df %>% select(-c(class))
  df_new2 <- df_new[, colSums(df_new>0) >9]
  df_new2$class <- test_df$class %>% as.factor()
  trainRowNumbers <- createDataPartition(df_new2$class, p=0.8, list = FALSE) 
  trainData <- df_new2[trainRowNumbers,]
  testData <- df_new2[-trainRowNumbers,]
  X = trainData %>% select(-c(class))
  Y = trainData$class
  preProcess_model <- preProcess(X, method=c("center", "scale")) # c("center", "scale")
  X <- predict(preProcess_model, newdata = X)
  X$class <- Y
  
  trControl = trainControl(
    method = "repeatedcv",                  
    number = 10, 
    repeats= 10,
    savePredictions = T,       
    classProbs = T,                 
    summaryFunction=twoClassSummary)
  
  tuneGrid <- expand.grid(mtry=seq(2,ncol(X), by=4))
  modellist <- list()
  for (ntree in c(10, 100)) {
        fit <- train(class ~ ., data=X, method='rf', trControl=trControl, tuneGrid = tuneGrid,
                   metric="ROC",
                   ntree=ntree)
      key <- toString(ntree)
      modellist[[key]] <- fit
  }
  # compare results
  results <- resamples(modellist)
  v_ROC <- summary(results)$statistics$ROC[,4]
  max_ROC <- summary(results)$statistics$ROC[,4] %>% max()
  NT <- names(v_ROC)[which(v_ROC == max_ROC)][1]
  # choose the best mtry 
  Best_tree <- modellist[names(modellist) == NT][[1]]
  Best_mtry <- Best_tree$bestTune
  # using the best Ntree and mtry
  model_rf <- train(class ~ ., data=X, method='rf', trControl=trControl, ntree=as.numeric(NT), tuneGrid=Best_mtry, metric="ROC")
  return(model_rf)}

RF_test_out <- RF_test(df2e)

RF <- function(DF, pimp_feature="no"){
  set.seed(7)
  test_df <- {{DF}} %>% mutate(class = ifelse(cls == 1, "Y", "N")) %>% select(-c(cls))
  df_new <- test_df %>% select(-c(class))
  df_new2 <- df_new[, colSums(df_new>0) >9]
  df_new2$class <- test_df$class %>% as.factor()
  trainRowNumbers <- createDataPartition(df_new2$class, p=0.8, list = FALSE) 
  trainData <- df_new2[trainRowNumbers,]
  testData <- df_new2[-trainRowNumbers,]
  X = trainData %>% select(-c(class))
  Y = trainData$class
  preProcess_model <- preProcess(X, method=c("center", "scale")) # c("center", "scale")
  X <- predict(preProcess_model, newdata = X)
  X$class <- Y
  
  trControl = trainControl(
    method = "repeatedcv",                  
    number = 10, 
    repeats= 10,
    savePredictions = T,      
    classProbs = T,                
    summaryFunction=twoClassSummary)
  
  tuneGrid <- expand.grid(mtry=seq(2,ncol(X), by=4))
  modellist <- list()
  for (ntree in c(10, 100)) {
        fit <- train(class ~ ., data=X, method='rf', trControl=trControl, tuneGrid = tuneGrid,
                   metric="ROC",
                   ntree=ntree)
      key <- toString(ntree)
      modellist[[key]] <- fit
  }
  # compare results
  results <- resamples(modellist)
  v_ROC <- summary(results)$statistics$ROC[,4]
  max_ROC <- summary(results)$statistics$ROC[,4] %>% max()
  NT <- names(v_ROC)[which(v_ROC == max_ROC)][1]
  # choose the best mtry 
  Best_tree <- modellist[names(modellist) == NT][[1]]
  Best_mtry <- Best_tree$bestTune
  # using the best Ntree and mtry
  model_rf <- train(class ~ ., data=X, method='rf', trControl=trControl, ntree=as.numeric(NT), tuneGrid=Best_mtry, metric="ROC")
  
  p2 <- varImp(model_rf)$importance %>%
    as.data.frame() %>% 
    rownames_to_column() %>% 
    arrange(Overall) %>% 
    mutate(rowname = forcats::fct_inorder(rowname)) %>% 
    set_colnames(c("viruses", "Importance")) %>% 
    ggplot(aes(x=viruses, y=Importance))+
    geom_segment(aes(x=viruses, xend=viruses, y=0, yend=Importance), color="skyblue") +
    geom_point(color="blue", size=1.5, alpha=0.6) +
    theme_light() +
    coord_flip() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.border = element_blank(),
      axis.ticks.y = element_blank())

  testData2 <- predict(preProcess_model, testData)
  predicted <- predict(model_rf, testData2)
  # Compute the confusion matrix
  confusionMatrix_DOCK8 = confusionMatrix(reference = testData$class, data = predicted, mode='everything', positive='Y')
  # create a list to store performance
  Performance_l <- list()
  Performance_l[[paste(deparse(substitute(DF)),"dock8_test_accu", sep = "_")]] = confusionMatrix_DOCK8$overall[["Accuracy"]]
  Performance_l[[paste(deparse(substitute(DF)),"model", sep = "_")]] = paste(model_rf$results[["ROC"]], model_rf$results[["Sens"]], model_rf$results[["Spec"]], sep = ":")
  Performance_l[["final_model"]] = model_rf
  print(p2)
  print(model_rf$finalModel)
  return(Performance_l)
}

try_comb <- function(topn=20){
  topn <- varImp(RF_test_out)$importance %>%
    as.data.frame() %>% 
    rownames_to_column() %>% 
    arrange(Overall) %>% 
    mutate(rowname = forcats::fct_inorder(rowname)) %>% 
    set_colnames(c("viruses", "Importance")) %>% arrange(-Importance) %>% head(n={{topn}}) %>% data.frame()
  
  topn$viruses <- gsub("`", '', topn$viruses, fixed=TRUE)
  topn <- topn$viruses
  df2e_new <- df2e[, colnames(df2e) %in% c(topn, "cls")]
  result <- RF(df2e_new)
  return(result)
}

final_module <- try_comb(12)

g_ROC <- ggplot(final_module$final_model$pred, aes(m=Y, d=factor(obs, levels = c("N", "Y")))) +
  geom_roc(n.cuts = 0) + 
  coord_equal() +
  style_roc(theme = theme_grey) 

PROC <- g_ROC + annotate("text", x=0.75, y=0.25, label=paste("AUC =", round((calc_auc(g_ROC))$AUC, 2))) 

p2e_left <- varImp(final_module$final_model)$importance %>%
    as.data.frame() %>% 
    rownames_to_column() %>% 
    arrange(Overall) %>% 
    mutate(rowname = forcats::fct_inorder(rowname)) %>% 
    set_colnames(c("Viruses", "Importance")) %>% 
    ggplot(aes(x=Viruses, y=Importance))+
    geom_segment(aes(x=Viruses, xend=Viruses, y=0, yend=Importance), color="skyblue") +
    geom_point(color="blue", size=1.5, alpha=0.6) +
    theme_light() +
    coord_flip() +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      #panel.border = element_blank(),
      axis.ticks.y = element_blank()
    ) 

# extract important list
Imp_list <- varImp(final_module$final_model)$importance %>% 
  arrange(-Overall) %>% 
  rownames() %>% 
  str_replace("`", "") %>% 
  str_replace("`", "")

df2e2 <- read.delim("/Users/chey2/Desktop/DOCK8_paper_codes/Input_files/Fig2e2_input.txt", header = TRUE, sep = "\t", check.names = FALSE) # input

row_order <- rownames(df2e2)
col_Imp <- colorRamp2(c(0, 0.05, 0.1, 0.5, 10, 50, 100), c("#F7F7F7",  "#9970AB", "#C2A5CF", "#E7D4E8", "#A6DBA0", "#5AAE61", "#1B7837"))
column_split_Imp = c(rep("Pre-Tx", 24), rep("Post-Tx-offIS-12M", 12), rep("Post-Tx-offIS-24M", 12), rep("HVs", 14))
target_all_genus <- com_dock8_hv_Imp_list %>% select(Type, Genus) %>% unique()
row_split = rownames(df2e2)

p2e_right <- Heatmap(df2e2,
                     row_order = row_order,
                     row_names_side = "left",
                     show_row_dend = F, 
                     show_column_dend = F,
                     col = col_Imp,
                     row_split = factor(row_split, levels = row_split),
                     column_gap = unit(3, "mm"),
                     row_gap = unit(0.5, "mm"),
                     row_title = NULL,
                     column_split = factor(column_split_Imp, levels = c("Pre-Tx", "Post-Tx-offIS-12M", "Post-Tx-offIS-24M", "HVs")),
                     cluster_row_slices = FALSE,
                     cluster_column_slices = FALSE, 
                     column_title = NULL, 
                     cluster_columns = FALSE, 
                     cluster_rows = FALSE,
                     row_names_gp = gpar(fontsize = 6.5),
                     column_names_gp = gpar(fontsize = 6.5)) 

p2e_left
p2e_right
PROC
```







